#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.26.4'

In [4]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ashra/anaconda3/Library/include
    lib directory: C:/Users/ashra/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
M = np.zeros((10,10))
print(M.size * M.itemsize)

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [16]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [17]:
M = np.zeros(10)
M[4] = 1
M

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
M = np.arange(10, 50)
M

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
M = np.arange(10, 50)
print(M)
M = M[::-1]
M

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [24]:
M = np.arange(9).reshape(3, 3)
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [26]:
nz = np.nonzero([1,2,0,0,4,0])
nz

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
M = np.eye(3)
M

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [33]:
M = np.random.random((3, 3, 3))
M

array([[[0.41059463, 0.21540664, 0.88665948],
        [0.15704836, 0.09536726, 0.37353176],
        [0.57170253, 0.30172173, 0.65894651]],

       [[0.86938671, 0.9082231 , 0.21563456],
        [0.57032653, 0.42375859, 0.32328431],
        [0.46811076, 0.20009675, 0.57251532]],

       [[0.29343715, 0.34871731, 0.24494495],
        [0.3311969 , 0.39171552, 0.51658538],
        [0.92011713, 0.6223241 , 0.81334501]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
M = np.random.random((10, 10))
M.min(), M.max()

(0.026536720326635788, 0.9939894109757433)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
M = np.random.random(30)
Mmean = M.mean()
Mmean

0.5027414980757698

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [42]:
M = np.ones((10, 10))
M[1:-1, 1:-1] = 0
M

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
M = np.ones((5, 5))
M = np.pad(M, pad_width=1, mode='constant', constant_values=0)
M

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [45]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [46]:
M = np.diag(1 + np.arange(4), k=-1)
M

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [47]:
M = np.zeros((8, 8), dtype=int)
M[1::2, ::2] = 1
M[::2, 1::2] = 1
M

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 21. Create a checkerboard 8x8 matrix using the tile function (search on it )

In [48]:
M = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
M

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix knowing normalization = (x-min/max-min )

In [50]:
M = np.random.random((5, 5))
Mmax, Mmin = M.max(axis=1), M.min(axis=1)
M

array([[0.53175118, 0.5067561 , 0.10791888, 0.23654261, 0.05886372],
       [0.51281937, 0.57025614, 0.88488705, 0.73250164, 0.46281898],
       [0.08219689, 0.47125075, 0.9021497 , 0.9445413 , 0.41683544],
       [0.27404683, 0.34712108, 0.80186159, 0.59710778, 0.60370227],
       [0.69312866, 0.30535323, 0.92267346, 0.7968158 , 0.81036903]])

In [52]:
(M - Mmin)/( Mmax - Mmin)

array([[ 1.        ,  0.10409961,  0.02982798, -0.07105566, -0.39928955],
       [ 0.9599655 ,  0.25454938,  0.93082317,  0.86859037,  0.25507952],
       [ 0.0493419 ,  0.01997728,  0.95084145,  1.27032157,  0.18059057],
       [ 0.45504085, -0.27412142,  0.8345444 ,  0.6120726 ,  0.48329704],
       [ 1.3412598 , -0.3730814 ,  0.97464141,  0.99044023,  0.8180775 ]])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [57]:
M_5x3 = np.random.random((5, 3))

M_3x2 = np.random.random((3, 2))

np.dot(M_5x3, M_3x2)

array([[0.74275204, 0.91979434],
       [0.84197144, 0.99939745],
       [0.72800417, 0.94832044],
       [0.72537358, 1.32157945],
       [0.3428469 , 0.69593222]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
M = np.arange(10)
M[(3 < M) & (M < 8)] *= -1
M

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [66]:
# np.array(0) / np.array(0) -> NaN
# np.array(0) // np.array(0) -> 0
# np.array([np.nan]).astype(int).astype(float) -> -2147483648.0

#### 30. How to find common values between two arrays? (★☆☆)

In [67]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])

np.intersect1d(arr1, arr2)

array([4, 5])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [69]:
# No it's False NoN != 1j (complex number)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [72]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

yesterday, today, tomorrow

(numpy.datetime64('2024-07-12'),
 numpy.datetime64('2024-07-13'),
 numpy.datetime64('2024-07-14'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [74]:
start = np.datetime64('2016-07-01')
end = np.datetime64('2016-08-01')

np.arange(start, end, dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [80]:
A = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
B = np.array([5.0, 4.0, 3.0, 2.0, 1.0])

C = A+B
D = -A*0.5
C*D

array([ -3.,  -6.,  -9., -12., -15.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [81]:
arr = np.random.random(10) * 100

np.floor(arr)

array([68., 22., 81.,  4., 34., 87., 16., 60., 94., 63.])

In [82]:
np.ceil(arr) - 1

array([68., 22., 81.,  4., 34., 87., 16., 60., 94., 63.])

In [83]:
np.trunc(arr)

array([68., 22., 81.,  4., 34., 87., 16., 60., 94., 63.])

In [84]:
arr.astype(int)

array([68, 22, 81,  4, 34, 87, 16, 60, 94, 63])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [85]:
np.arange(5).reshape(1, 5) + np.zeros((5, 1))

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [88]:
def generate_integers():
    for i in range(10):
        yield i

np.array(list(generate_integers()))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [89]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [90]:
M = np.random.random(10)

np.sort(M)

array([0.02065751, 0.09904214, 0.17658066, 0.32659411, 0.47086806,
       0.47918813, 0.52768138, 0.67357166, 0.89310103, 0.9573067 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [95]:
M = np.random.random(10)
sum(M) # Faster 4 Times

5.309141776456344

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [109]:
A = np.random.random(10)
B = np.random.random(10)

np.array_equal(A, B)

False

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [111]:
M = np.random.random(10)

maxVal = np.max(M)

M[M == maxVal] = 0
M

array([0.16267122, 0.62577375, 0.17434559, 0.        , 0.04439589,
       0.0565491 , 0.58260432, 0.10217271, 0.2445003 , 0.12206705])

#### 49. How to print all the values of an array? (★★☆)

In [112]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [116]:
V = np.array([1.2, 3.5, 4.8, 6.1, 7.4, 9.7])

S = 5.0

idx = np.abs(V - S).argmin()

val = V[idx]

print(f"""
Vector: {V}
Scalar: {S}
Closest value: {val}
Index of closest value: {idx}
""")



Vector: [1.2 3.5 4.8 6.1 7.4 9.7]
Scalar: 5.0
Closest value: 4.8
Index of closest value: 2

